# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: "00 03 * * *"


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: get system time
      run: date
        
    - name: send message to kafka
      run: python3 sendKafka.py
      env:
        SERVER_NAME: ${{ secrets.SERVER_NAME }}
        SASL_MECH: ${{ secrets.SASL_MECH }}
        SSL_SEC: ${{ secrets.SSL_SEC }}
        SASL_USERNAME: ${{ secrets.SASL_USERNAME }}
        SASL_PASSD: ${{ secrets.SASL_PASSD }}

    - name: receive message to kafka
      run: python3 receiveKafka.py
      env:
        SERVER_NAME: ${{ secrets.SERVER_NAME }}
        SASL_MECH: ${{ secrets.SASL_MECH }}
        SSL_SEC: ${{ secrets.SSL_SEC }}
        SASL_USERNAME: ${{ secrets.SASL_USERNAME }}
        SASL_PASSD: ${{ secrets.SASL_PASSD }}
